name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libmagic1 tesseract-ocr poppler-utils

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio flake8
          pip install -e .  # Install package in editable mode

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --statistics

      - name: Run tests
        env:
          TESTING: "true"
          # Using dummy values for testing
          GROQ_API_KEY: "test_groq_key"
          TOGETHER_API_KEY: "test_together_key"
          DEEPSEEK_API_KEY: "test_deepseek_key"
          GEMINI_API_KEY: "test_gemini_key"
          OPENAI_API_KEY: "test_openai_key"
          AWS_ACCESS_KEY_ID: "test_aws_key_id"
          AWS_SECRET_ACCESS_KEY: "test_aws_secret_key"
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          python -m pytest tests/ -v
